// Radio candidates for the localhost-only audition lab.
//
// This list is deliberately separate from RADIO_STATIONS: candidates must earn
// their way into the production picker after a real browser listening test.

export type RadioAuditionCandidate = {
  id: string;
  name: string;
  region: string;
  country: string;
  icon: string;
  tagline: string;
  streamUrl: string;
  homepage: string;
  reason: string;
};

export const RADIO_AUDITION_CANDIDATES: RadioAuditionCandidate[] = [
  {
    id: 'freecodecamp',
    name: 'FreeCodeCamp Radio',
    region: 'Global',
    country: 'Internet',
    icon: '💻',
    tagline: 'Electronic · instrumental · dev focus',
    streamUrl: 'https://coderadio-admin-v2.freecodecamp.org/listen/coderadio/radio.mp3',
    homepage: 'https://coderadio.freecodecamp.org/',
    reason: 'A natural PuffBreak default: focused electronic music, minimal interruption, and a strong developer-community identity.',
  },
  {
    id: 'radioparadise-main',
    name: 'Radio Paradise Main Mix',
    region: 'Global',
    country: 'USA',
    icon: '🌈',
    tagline: 'Eclectic · rock · world · electronic',
    streamUrl: 'https://stream.radioparadise.com/mp3-192',
    homepage: 'https://radioparadise.com/',
    reason: 'One of the strongest human-curated internet stations: adventurous without becoming abrasive, with broad international appeal.',
  },
  {
    id: 'radioparadise-mellow',
    name: 'Radio Paradise Mellow Mix',
    region: 'Global',
    country: 'USA',
    icon: '🌙',
    tagline: 'Mellow · acoustic · soft electronic',
    streamUrl: 'https://stream.radioparadise.com/mellow-192',
    homepage: 'https://radioparadise.com/',
    reason: 'Exceptionally aligned with a three-minute reset: warm, low-friction selections that work as atmosphere rather than demanding attention.',
  },
  {
    id: 'kexp',
    name: 'KEXP',
    region: 'North America',
    country: 'USA',
    icon: '🎙️',
    tagline: 'Indie · alternative · global discovery',
    streamUrl: 'https://kexp-mp3-128.streamguys1.com/kexp128.mp3',
    homepage: 'https://www.kexp.org/listen/',
    reason: 'World-class human music discovery with real personality. Kept as the energetic, culture-forward alternative to passive chill streams.',
  },
  {
    id: 'kcrw-eclectic24',
    name: 'KCRW Eclectic24',
    region: 'North America',
    country: 'USA',
    icon: '🌴',
    tagline: 'Eclectic · indie · soul · electronic',
    streamUrl: 'https://streams.kcrw.com/e24_mp3',
    homepage: 'https://www.kcrw.com/shows/eclectic24',
    reason: 'A polished 24-hour all-music feed from respected Los Angeles selectors; stylish, varied, and especially good for creative-work breaks.',
  },
  {
    id: 'king-fm',
    name: 'Classical KING FM',
    region: 'North America',
    country: 'USA',
    icon: '🎻',
    tagline: 'Classical · calm · orchestral',
    streamUrl: 'https://classicalking.streamguys1.com/king-fm-aac-128k',
    homepage: 'https://king.org/listen/',
    reason: 'A high-quality classical option gives the catalogue genuine calm and sophistication instead of filling every slot with chillhop or pop.',
  },
  {
    id: 'fip',
    name: 'FIP',
    region: 'Europe',
    country: 'France',
    icon: '🇫🇷',
    tagline: 'Eclectic · chanson · jazz · world',
    streamUrl: 'https://icecast.radiofrance.fr/fip-midfi.mp3',
    homepage: 'https://www.radiofrance.fr/fip',
    reason: 'Possibly the best aesthetic match in the set: graceful genre transitions, tasteful French curation, and almost no sonic clutter.',
  },
  {
    id: 'fip-jazz',
    name: 'FIP Jazz',
    region: 'Europe',
    country: 'France',
    icon: '🎷',
    tagline: 'Jazz · soul · modern classics',
    streamUrl: 'https://icecast.radiofrance.fr/fipjazz-midfi.mp3',
    homepage: 'https://www.radiofrance.fr/fip/radio-jazz',
    reason: 'Smooth but never generic; it adds an evening café mood that suits the chai, library, rooftop, and late-work environments.',
  },
  {
    id: 'fip-groove',
    name: 'FIP Groove',
    region: 'Europe',
    country: 'France',
    icon: '🪩',
    tagline: 'Funk · soul · disco · groove',
    streamUrl: 'https://icecast.radiofrance.fr/fipgroove-midfi.mp3',
    homepage: 'https://www.radiofrance.fr/fip/radio-groove',
    reason: 'The upbeat option with taste: warm basslines and movement without the harshness of a generic commercial dance station.',
  },
  {
    id: 'fip-rock',
    name: 'FIP Rock',
    region: 'Europe',
    country: 'France',
    icon: '🎸',
    tagline: 'Alternative · classic · indie rock',
    streamUrl: 'https://icecast.radiofrance.fr/fiprock-midfi.mp3',
    homepage: 'https://www.radiofrance.fr/fip/radio-rock',
    reason: 'A more energetic room without falling into algorithmic greatest-hits repetition; curated enough to feel premium.',
  },
  {
    id: 'swiss-pop',
    name: 'Radio Swiss Pop',
    region: 'Europe',
    country: 'Switzerland',
    icon: '🇨🇭',
    tagline: 'Pop · melodic · familiar',
    streamUrl: 'https://stream.srg-ssr.ch/srgssr/rsp/mp3/128',
    homepage: 'https://www.radioswisspop.ch/',
    reason: 'A dependable, approachable counterweight to the more adventurous stations; melodic, cleanly presented, and officially streamed.',
  },
  {
    id: 'swiss-jazz',
    name: 'Radio Swiss Jazz',
    region: 'Europe',
    country: 'Switzerland',
    icon: '🎺',
    tagline: 'Jazz · blues · swing',
    streamUrl: 'https://stream.srg-ssr.ch/srgssr/rsj/mp3/128',
    homepage: 'https://www.radioswissjazz.ch/',
    reason: 'Relaxed, mature and highly usable as background listening; an excellent fit for quiet breaks without sounding like spa music.',
  },
  {
    id: 'fluxfm',
    name: 'FluxFM',
    region: 'Europe',
    country: 'Germany',
    icon: '🇩🇪',
    tagline: 'Indie · alternative · electronic',
    streamUrl: 'https://channels.fluxfm.de/FluxFM/externalembedflxhp/stream.mp3',
    homepage: 'https://www.fluxfm.de/',
    reason: 'Berlin energy and contemporary discovery give the list a sharper European identity than another anonymous hits channel would.',
  },
  {
    id: 'los40',
    name: 'LOS40',
    region: 'Europe',
    country: 'Spain',
    icon: '🇪🇸',
    tagline: 'Spanish pop · Latin hits · chart music',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40.mp3',
    homepage: 'https://los40.com/',
    reason: 'A recognisable Spanish-language mainstream option. It is here to test whether users want familiar hits alongside the more curated stations.',
  },
  {
    id: 'radio-mirchi',
    name: 'Radio Mirchi',
    region: 'South Asia',
    country: 'India',
    icon: '🇮🇳',
    tagline: 'Bollywood · Hindi hits',
    streamUrl: 'https://eu8.fastcast4u.com/proxy/clyedupq/stream',
    homepage: 'https://mirchi.in/',
    reason: 'The most recognisable Indian music brand in the candidate set; culturally relevant to PuffBreak and essential to test with the core audience.',
  },
  {
    id: 'bollywood-now',
    name: 'Bollywood Now',
    region: 'South Asia',
    country: 'India',
    icon: '🎬',
    tagline: 'Current Bollywood · Hindi pop',
    streamUrl: 'https://drive.uber.radio/uber/bollywoodnow/icecast.audio',
    homepage: 'https://uber.radio/',
    reason: 'A cleaner music-first alternative to presenter-heavy FM: current Bollywood energy with fewer interruptions during a short break.',
  },
  {
    id: 'bollywood-evergreen',
    name: 'Bollywood Evergreen',
    region: 'South Asia',
    country: 'India',
    icon: '🌼',
    tagline: 'Classic Hindi · nostalgic · melodic',
    streamUrl: 'https://stream.zeno.fm/n2fd0edh9k8uv',
    homepage: 'https://zeno.fm/',
    reason: 'Nostalgia is powerful in a comfort product. This tests whether mellow classics work better than current chart music for chai breaks.',
  },
  {
    id: 'japan-city-pop',
    name: 'Japan City Pop',
    region: 'East Asia',
    country: 'Japan',
    icon: '🇯🇵',
    tagline: 'City pop · retro · neon',
    streamUrl: 'https://play.streamafrica.net/japancitypop',
    homepage: 'https://www.radio-browser.info/',
    reason: 'Almost purpose-built for PuffBreak’s visual language: glossy, nostalgic and instantly atmospheric for rooftop or metro rooms.',
  },
  {
    id: 'r-a-dio',
    name: 'R/a/dio',
    region: 'East Asia',
    country: 'Japan',
    icon: '🌸',
    tagline: 'Anime · J-pop · electronic',
    streamUrl: 'https://relay0.r-a-d.io/main.mp3',
    homepage: 'https://r-a-d.io/',
    reason: 'A long-running community station with a distinct identity and highly engaged niche audience; playful without feeling like generic pop radio.',
  },
  {
    id: 'gensokyo',
    name: 'Gensokyo Radio',
    region: 'East Asia',
    country: 'Japan',
    icon: '⛩️',
    tagline: 'Touhou · game music · doujin',
    streamUrl: 'https://stream.gensokyoradio.net/3',
    homepage: 'https://gensokyoradio.net/',
    reason: 'A distinctive gaming-culture option with melodic energy. Worth testing because PuffBreak already speaks naturally to developers and gamers.',
  },
  {
    id: 'bigb-kpop',
    name: 'Big B Radio K-Pop',
    region: 'East Asia',
    country: 'South Korea',
    icon: '🇰🇷',
    tagline: 'K-pop · Korean hits',
    streamUrl: 'https://antares.dribbcast.com/proxy/kpop?mp=/s',
    homepage: 'https://bigbradio.net/',
    reason: 'K-pop has a huge global audience; this gives the test a genuinely popular East Asian choice rather than only niche Japanese stations.',
  },
  {
    id: 'hotmix-medina',
    name: 'Hotmix Medina',
    region: 'Middle East',
    country: 'Regional',
    icon: '🌙',
    tagline: 'Arabic · Persian · contemporary hits',
    streamUrl: 'https://streaming.hotmixradio.com/hotmix-medina-en-mp3?provider=radiobrowse',
    homepage: 'https://www.hotmixradio.com/',
    reason: 'A polished, music-led bridge across Arabic and Persian pop; regionally distinctive while still accessible to a global listener.',
  },
  {
    id: 'amr-diab',
    name: 'Amr Diab Radio',
    region: 'Middle East',
    country: 'Egypt',
    icon: '🇪🇬',
    tagline: 'Egyptian pop · Arabic pop',
    streamUrl: 'https://stream-40.zeno.fm/xa4yhh4k838uv',
    homepage: 'https://zeno.fm/',
    reason: 'A focused Egyptian-pop mood with immediate warmth and recognisable regional character; useful for testing artist-led versus mixed stations.',
  },
  {
    id: 'amapiano-fm',
    name: 'Amapiano FM',
    region: 'Africa',
    country: 'South Africa',
    icon: '🇿🇦',
    tagline: 'Amapiano · deep house · South African',
    streamUrl: 'https://stream.zeno.fm/xs6zeac1ts8uv',
    homepage: 'https://zeno.fm/',
    reason: 'Amapiano is one of the most globally influential sounds from Africa right now; rhythmic, warm and ideal for an energising break.',
  },
  {
    id: 'major-fm',
    name: 'MajorFM',
    region: 'Africa',
    country: 'Nigeria',
    icon: '🇳🇬',
    tagline: 'Afrobeats · R&B · hip-hop · lounge',
    streamUrl: 'https://stream.zeno.fm/pkza99xshkhvv',
    homepage: 'https://zeno.fm/',
    reason: 'Adds Nigerian and Afrobeats-adjacent energy to prevent the Africa section being reduced to a single South African genre.',
  },
  {
    id: 'bossa-jazz-brasil',
    name: 'Bossa Jazz Brasil',
    region: 'Latin America',
    country: 'Brazil',
    icon: '🇧🇷',
    tagline: 'Bossa nova · Brazilian jazz · samba',
    streamUrl: 'https://centova5.transmissaodigital.com:20104/live',
    homepage: 'https://www.radio-browser.info/',
    reason: 'Bossa nova is almost an ideal break-room sound: unmistakably Brazilian, elegant, sunny and relaxed without becoming anonymous background music.',
  },
  {
    id: 'saudade-fm',
    name: 'Rádio Saudade',
    region: 'Latin America',
    country: 'Brazil',
    icon: '🌅',
    tagline: 'Brazilian oldies · romantic · nostalgic',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/SAUDADE_FMAAC.aac',
    homepage: 'https://www.saudadefm.com.br/',
    reason: 'A softer, nostalgic Brazilian mood that could work beautifully in sunset and chai rooms; selected for emotion rather than chart relevance.',
  },
  {
    id: 'abc-jazz',
    name: 'ABC Jazz',
    region: 'Oceania',
    country: 'Australia',
    icon: '🇦🇺',
    tagline: 'Jazz · Australian artists · modern classics',
    streamUrl: 'https://live-radio01.mediahubaustralia.com/JAZW/mp3/',
    homepage: 'https://www.abc.net.au/jazz',
    reason: 'A trusted public-radio music service with strong local representation; calm enough for focus but more contemporary than generic jazz radio.',
  },
  {
    id: 'triple-j',
    name: 'triple j',
    region: 'Oceania',
    country: 'Australia',
    icon: '🦘',
    tagline: 'Alternative · Australian · new music',
    streamUrl: 'https://abc.streamguys1.com/live/triplejnsw/icecast.audio',
    homepage: 'https://www.abc.net.au/triplej',
    reason: 'Australia’s essential youth-music discovery station; energetic and recognisable, included to test whether presenter-led music belongs in PuffBreak.',
  },
  {
    id: 'rnz-concert',
    name: 'RNZ Concert',
    region: 'Oceania',
    country: 'New Zealand',
    icon: '🎼',
    tagline: 'Classical · contemporary · live performance',
    streamUrl: 'https://stream-ice.radionz.co.nz/concert.mp3',
    homepage: 'https://www.rnz.co.nz/concert',
    reason: 'A serene, culturally grounded New Zealand option that gives the collection breathing room and suits deep-focus or silent-room users.',
  },
  {
    id: '181-old-school',
    name: '181.FM Old School',
    region: 'North America',
    country: 'USA',
    icon: '📼',
    tagline: 'Old-school hip-hop · R&B · rap',
    streamUrl: 'https://listen.181fm.com/181-oldschool_128k.mp3',
    homepage: 'https://www.181.fm/',
    reason: 'The dependable nostalgia lane: familiar hip-hop and R&B with enough rhythm for a lift, without the volatility of a current-chart feed.',
  },
  {
    id: '181-the-beat',
    name: '181.FM The Beat',
    region: 'North America',
    country: 'USA',
    icon: '🔥',
    tagline: 'Current hip-hop · R&B · rap',
    streamUrl: 'https://listen.181fm.com/181-beat_128k.mp3',
    homepage: 'https://www.181.fm/',
    reason: 'The modern counterpart to Old School: a recognisable, high-energy rotation for users who want current rap and R&B rather than background chill.',
  },
  {
    id: 'radio-nova',
    name: 'Radio Nova',
    region: 'Europe',
    country: 'France',
    icon: '🪩',
    tagline: 'Future soul · hip-hop · global grooves',
    streamUrl: 'https://novazz.ice.infomaniak.ch/novazz-128.mp3',
    homepage: 'https://www.nova.fr/',
    reason: 'A genuinely tasteful selector station: hip-hop and soul sit beside global sounds, making discovery feel cultured instead of algorithmically generic.',
  },
  {
    id: 'flava-nz',
    name: 'Flava',
    region: 'Oceania',
    country: 'New Zealand',
    icon: '🌊',
    tagline: 'Old-school hip-hop · R&B favourites',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/NZME_08AAC.aac',
    homepage: 'https://www.flava.co.nz/',
    reason: 'A warm, personality-led old-school mix with a New Zealand point of view; it broadens the collection without duplicating a generic US throwback feed.',
  },
  {
    id: 'los40-urban',
    name: 'LOS40 Urban',
    region: 'Europe',
    country: 'Spain',
    icon: '🌐',
    tagline: 'Latin urban · rap · reggaeton',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_URBAN.mp3',
    homepage: 'https://los40.com/los40_urban/',
    reason: 'Latin urban deserves its own lane rather than being filed under generic pop; this adds Spanish-language rap and reggaeton from a major music brand.',
  },
  {
    id: 'rap-lbeldi',
    name: 'Rap Lbeldi',
    region: 'Africa',
    country: 'Morocco',
    icon: '🇲🇦',
    tagline: 'Moroccan rap · Maghrebi hip-hop',
    streamUrl: 'https://stream.zeno.fm/ivdufrl7q0quv',
    homepage: 'https://zeno.fm/',
    reason: 'A sharp regional choice that makes “global rap” real: Moroccan and Maghrebi voices instead of another English-language station with a world label.',
  },
  {
    id: 'bhaktisudha',
    name: 'Bhaktisudha',
    region: 'South Asia',
    country: 'India',
    icon: '🪷',
    tagline: 'Bhajan · devotional · Indian classical',
    streamUrl: 'https://n0a.radiojar.com/cfqyfcspcv8uv',
    homepage: 'https://www.radiojar.com/radio/bhaktisudha',
    reason: 'A quiet devotional lane for Hindi listeners: recognisable bhajans and classical colour that suit a reflective break rather than a loud religious broadcast.',
  },
  {
    id: 'hotmix-lofi',
    name: 'Hotmix Lo-Fi',
    region: 'Global',
    country: 'France',
    icon: '🌙',
    tagline: 'Lo-fi · chillhop · instrumental',
    streamUrl: 'https://streaming.hotmixradio.com/hotmix-lofi-en-mp3?provider=radiobrowser',
    homepage: 'https://hotmixradio.com/',
    reason: 'One intentional lo-fi choice, not a wall of interchangeable beat streams: reliable delivery, no presenters, and the right pace for focus or decompression.',
  },
  {
    id: 'city-fm-89',
    name: 'City FM 89',
    region: 'South Asia',
    country: 'Pakistan',
    icon: '🇵🇰',
    tagline: 'Pakistani pop · contemporary · English and Urdu',
    streamUrl: 'https://radio.cityfm89.com/stream',
    homepage: 'https://cityfm89.com/',
    reason: 'A strong, contemporary Pakistani signal with real local identity; it fills an important audience gap without reducing Pakistan to Bollywood spillover.',
  },
  {
    id: 'sbs-popasia',
    name: 'SBS PopAsia',
    region: 'East Asia',
    country: 'Australia',
    icon: '✨',
    tagline: 'Asian pop · K-pop · J-pop',
    streamUrl: 'https://sbs-ice.streamguys1.com/sbs-popasia-sbs-web',
    homepage: 'https://www.sbs.com.au/audio/music/popasia',
    reason: 'A public-broadcaster Asian-pop service with breadth across Korea, Japan and China—more credible and varied than another narrow fandom stream.',
  },
  {
    id: '181-awesome-80s',
    name: '181.FM Awesome 80s',
    region: 'North America',
    country: 'USA',
    icon: '📺',
    tagline: '80s pop · new wave · familiar favourites',
    streamUrl: 'https://listen.181fm.com/181-awesome80s_128k.mp3',
    homepage: 'https://www.181.fm/',
    reason: 'A broad nostalgia station for regular listeners who want instant familiarity; it balances the more specialist jazz, indie and regional choices.',
  },
];

export const RADIO_AUDITION_REGIONS = [
  'Global',
  'North America',
  'Europe',
  'South Asia',
  'East Asia',
  'Middle East',
  'Africa',
  'Latin America',
  'Oceania',
] as const;
